tokens:
  - chainName: bsc
    standard: EvmHypCollateral
    decimals: 18
    symbol: USDT
    name: Tether USD
    addressOrDenom: "0xbb9F2Dc93C00e818eECb4A12B661fd2c9817E301"
    collateralAddressOrDenom: "0x55d398326f99059fF775485246999027B3197955"
    connections:
      - token: ethereum|kasplex|0xBbC4a4Ab915E04a833aefa872A6d19eCac372134
      - token: ethereum|ethereum|0x63692627A88068D50Ba5bbb0225C16ebD007fEcD
    logoURI: /deployments/warp_routes/USDT/logo.svg
  - chainName: kasplex
    standard: EvmHypSynthetic
    decimals: 18
    symbol: USDT
    name: Tether USD
    addressOrDenom: "0xBbC4a4Ab915E04a833aefa872A6d19eCac372134"
    connections:
      - token: ethereum|bsc|0xbb9F2Dc93C00e818eECb4A12B661fd2c9817E301
      - token: ethereum|ethereum|0x63692627A88068D50Ba5bbb0225C16ebD007fEcD
    logoURI: /deployments/warp_routes/USDT/logo.svg
  - chainName: ethereum
    standard: EvmHypCollateral
    decimals: 6
    symbol: USDT
    name: Tether USD
    addressOrDenom: "0x63692627A88068D50Ba5bbb0225C16ebD007fEcD"
    collateralAddressOrDenom: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
    connections:
      - token: ethereum|bsc|0xbb9F2Dc93C00e818eECb4A12B661fd2c9817E301
      - token: ethereum|kasplex|0xBbC4a4Ab915E04a833aefa872A6d19eCac372134
    logoURI: /deployments/warp_routes/USDT/logo.svg
