tokens:
  - chainName: kasplex
    standard: EvmHypSynthetic
    decimals: 18
    logoURI: /deployments/warp_routes/USDT/logo.svg
    symbol: USDT
    name: Tether USD
    addressOrDenom: "0xBbC4a4Ab915E04a833aefa872A6d19eCac372134"
    connections:
      - token: ethereum|bsc|0xbb9F2Dc93C00e818eECb4A12B661fd2c9817E301
  - chainName: bsc
    standard: EvmHypCollateral
    decimals: 18
    logoURI: /deployments/warp_routes/USDT/logo.svg
    symbol: USDT
    name: Tether USD
    addressOrDenom: "0xbb9F2Dc93C00e818eECb4A12B661fd2c9817E301"
    collateralAddressOrDenom: "0x55d398326f99059fF775485246999027B3197955"
    connections:
      - token: ethereum|kasplex|0xBbC4a4Ab915E04a833aefa872A6d19eCac372134
