tokens:
  - chainName: kasplextestnet
    standard: EvmHypSynthetic
    decimals: 18
    symbol: USDT
    name: USDT
    addressOrDenom: "0x552F28bd91106bA1EE5d44cc2324cfe58ddFcE8E"
    connections:
      - token: ethereum|bsctestnet|0x41269888F8c51F35CB532Ac20856D288ec6e0644
      - token: ethereum|basesepolia|0x1AbcD0a143595Db06f69926667F1BBC2E7Ef70c7
  - chainName: bsctestnet
    standard: EvmHypCollateral
    decimals: 18
    symbol: USDT
    name: Tether USD
    addressOrDenom: "0x41269888F8c51F35CB532Ac20856D288ec6e0644"
    collateralAddressOrDenom: "0xb97aDD318e75F98972f95323ce0A035E31784c4E"
    connections:
      - token: ethereum|kasplextestnet|0x552F28bd91106bA1EE5d44cc2324cfe58ddFcE8E
      - token: ethereum|basesepolia|0x1AbcD0a143595Db06f69926667F1BBC2E7Ef70c7
  - chainName: basesepolia
    standard: EvmHypCollateral
    decimals: 6
    symbol: USDT
    name: USDT
    addressOrDenom: "0x1AbcD0a143595Db06f69926667F1BBC2E7Ef70c7"
    collateralAddressOrDenom: "0xB6F08394a2f570C5a98F4D5a787ec263Ddfad2de"
    connections:
      - token: ethereum|kasplextestnet|0x552F28bd91106bA1EE5d44cc2324cfe58ddFcE8E
      - token: ethereum|bsctestnet|0x41269888F8c51F35CB532Ac20856D288ec6e0644
