tokens:
  - chainName: kasplextestnet
    standard: EvmHypSynthetic
    decimals: 18
    symbol: USDT
    name: USDT
    addressOrDenom: "0x7E834a631a294e32FF7fDC5814dB5393E7aF58CC"
    connections:
      - token: ethereum|basesepolia|0x150F5215DB18127a1d80765176B76d411f02a56F
  - chainName: basesepolia
    standard: EvmHypCollateral
    decimals: 18
    symbol: USDT
    name: USDT
    addressOrDenom: "0x150F5215DB18127a1d80765176B76d411f02a56F"
    collateralAddressOrDenom: "0x5365933D533b127aEbF845777e6fD6AE2A942f58"
    connections:
      - token: ethereum|kasplextestnet|0x7E834a631a294e32FF7fDC5814dB5393E7aF58CC
