tokens:
  - chainName: kasplextestnet
    standard: EvmHypCollateral
    decimals: 18
    symbol: USDT
    name: Tether USD
    addressOrDenom: "0x261774bA5794de56eE163fd96C1900bf9484687B"
    collateralAddressOrDenom: "0x62a331a0582FEbb081863F6773b8510A7D71B0a6"
    connections:
      - token: ethereum|sepolia|0x69C3dEB37A88BCAe9f65A2e0D613bcdD2E31d13A
    logoURI: /deployments/warp_routes/USDT/logo.svg
  - chainName: sepolia
    standard: EvmHypSynthetic
    decimals: 18
    symbol: USDT
    name: Tether USD
    addressOrDenom: "0x69C3dEB37A88BCAe9f65A2e0D613bcdD2E31d13A"
    connections:
      - token: ethereum|kasplextestnet|0x261774bA5794de56eE163fd96C1900bf9484687B
    logoURI: /deployments/warp_routes/USDT/logo.svg
