tokens:
  - chainName: kasplextestnet
    standard: EvmHypSynthetic
    decimals: 18
    symbol: USDT
    name: Tether USD
    addressOrDenom: "0x62a331a0582FEbb081863F6773b8510A7D71B0a6"
    connections:
      - token: ethereum|bsctestnet|0xEe9DAAE997518C778d24C3D80B92A9CdF198b217
      - token: ethereum|basesepolia|0xad71Cf5b27Cc93843E88ba2871e92C28F1FF08D4
    logoURI: /deployments/warp_routes/USDT/logo.svg
  - chainName: basesepolia
    standard: EvmHypCollateral
    decimals: 6
    symbol: USDT
    name: Tether USD
    addressOrDenom: "0xad71Cf5b27Cc93843E88ba2871e92C28F1FF08D4"
    collateralAddressOrDenom: "0xB6F08394a2f570C5a98F4D5a787ec263Ddfad2de"
    connections:
      - token: ethereum|kasplextestnet|0x62a331a0582FEbb081863F6773b8510A7D71B0a6
      - token: ethereum|bsctestnet|0xEe9DAAE997518C778d24C3D80B92A9CdF198b217
    logoURI: /deployments/warp_routes/USDT/logo.svg
  - chainName: bsctestnet
    standard: EvmHypCollateral
    decimals: 18
    symbol: USDT
    name: Tether USD
    addressOrDenom: "0xEe9DAAE997518C778d24C3D80B92A9CdF198b217"
    collateralAddressOrDenom: "0xb97aDD318e75F98972f95323ce0A035E31784c4E"
    connections:
      - token: ethereum|kasplextestnet|0x62a331a0582FEbb081863F6773b8510A7D71B0a6
      - token: ethereum|basesepolia|0xad71Cf5b27Cc93843E88ba2871e92C28F1FF08D4
    logoURI: /deployments/warp_routes/USDT/logo.svg
