tokens:
  - chainName: kasplextestnet
    standard: EvmHypSynthetic
    decimals: 18
    symbol: USDT
    name: USDT
    addressOrDenom: "0x46dAC32BBce9da2eC04dE81c9a741CB9ecE8E331"
    connections:
      - token: ethereum|basesepolia|0x7eedC40a3fcb507dcE07330398Dc65C460B03865
  - chainName: basesepolia
    standard: EvmHypCollateral
    decimals: 18
    symbol: USDT
    name: USDT
    addressOrDenom: "0x7eedC40a3fcb507dcE07330398Dc65C460B03865"
    collateralAddressOrDenom: "0x5365933D533b127aEbF845777e6fD6AE2A942f58"
    connections:
      - token: ethereum|kasplextestnet|0x46dAC32BBce9da2eC04dE81c9a741CB9ecE8E331
