tokens:
  - chainName: kasplextestnet
    standard: EvmHypSynthetic
    decimals: 18
    symbol: USDT
    name: USDT
    addressOrDenom: "0x5B89DdA422Ed47979B08727aD5d9d7A3514D259B"
    connections:
      - token: ethereum|basesepolia|0x23B192092aEA67A1Bb0C5968a81b7677B1bc1eF7
  - chainName: basesepolia
    standard: EvmHypCollateral
    decimals: 18
    symbol: USDT
    name: USDT
    addressOrDenom: "0x23B192092aEA67A1Bb0C5968a81b7677B1bc1eF7"
    collateralAddressOrDenom: "0x5365933D533b127aEbF845777e6fD6AE2A942f58"
    connections:
      - token: ethereum|kasplextestnet|0x5B89DdA422Ed47979B08727aD5d9d7A3514D259B
