tokens:
  - chainName: igratestnet
    standard: EvmHypSynthetic
    decimals: 18
    symbol: USDT
    name: USDT
    addressOrDenom: "0xaf27F006C81fdE2D876282Cd6Cb370338d73B246"
    connections:
      - token: ethereum|sepolia|0xD9BdA395724b008510974253B17DE84Ea2ccFFC9
    logoURI: /deployments/warp_routes/USDT/logo.svg
  - chainName: sepolia
    standard: EvmHypCollateral
    decimals: 18
    symbol: USDT
    name: USDT
    addressOrDenom: "0xD9BdA395724b008510974253B17DE84Ea2ccFFC9"
    collateralAddressOrDenom: "0xe443273F4ed0752B1140AE26fB052461b1f1aAbC"
    connections:
      - token: ethereum|igratestnet|0xaf27F006C81fdE2D876282Cd6Cb370338d73B246
    logoURI: /deployments/warp_routes/USDT/logo.svg
