defaultHook:
  type: merkleTreeHook
defaultIsm:
  relayer: "0xae44946077d5c32ffbdccf97dddda689904caaaa"
  type: trustedRelayerIsm
owner: "0xae44946077d5c32ffbdccf97dddda689904caaaa"
proxyAdmin:
  owner: "0xae44946077d5c32ffbdccf97dddda689904caaaa"
requiredHook:
  hooks:
    - beneficiary: "0xaE44946077D5C32FFBDcCF97ddDdA689904caAAa"
      maxProtocolFee: "1000000000000000000"
      owner: "0xaE44946077D5C32FFBDcCF97ddDdA689904caAAa"
      protocolFee: "25000000000000000"
      type: protocolFee
    - beneficiary: "0xaE44946077D5C32FFBDcCF97ddDdA689904caAAa"
      oracleConfig:
        base:
          gasPrice: "1327120"
          tokenDecimals: 18
          tokenExchangeRate: "11000000000"
        bsc:
          gasPrice: "50000000"
          tokenDecimals: 18
          tokenExchangeRate: "2983999148"
        kasplex:
          gasPrice: "2001000000000"
          tokenDecimals: 18
          tokenExchangeRate: "164676"
      oracleKey: "0xaE44946077D5C32FFBDcCF97ddDdA689904caAAa"
      overhead:
        base: 75000
        bsc: 75000
        kasplex: 75000
      owner: "0xaE44946077D5C32FFBDcCF97ddDdA689904caAAa"
      type: interchainGasPaymaster
  type: aggregationHook

