defaultHook:
  type: merkleTreeHook
defaultIsm:
  relayer: "0x1900c5B15268F13BB4e462f54F5EDD6834C47348"
  type: trustedRelayerIsm
owner: "0x1900c5B15268F13BB4e462f54F5EDD6834C47348"
proxyAdmin:
  owner: "0x1900c5B15268F13BB4e462f54F5EDD6834C47348"
requiredHook:
  beneficiary: "0x1900c5B15268F13BB4e462f54F5EDD6834C47348"
  maxProtocolFee: "100000000000000000"
  owner: "0x1900c5B15268F13BB4e462f54F5EDD6834C47348"
  protocolFee: "0"
  type: protocolFee

